### ISSUE TITLE
Week3

### ISSUE THREAD

**Issue by NickyXiao** [algorithm017/algorithm017#20]

**Comment by NickyXiao** [comment]
#学号: G20200388020561
#姓名:Senble
#班级:17期3组
#语言:java
#作业链接:https://github.com/NickyXiao/algorithm017/tree/master/Week_03

**Comment by wanmenglei** [comment]
#学号:G20200447010401
#姓名:万梦磊
#班级:17期3组
#语言:javascript
#作业链接:https://github.com/wanmenglei/algorithm017/tree/master/Week_03
#总结链接:https://github.com/wanmenglei/algorithm017/blob/master/Week_03/README.md
