### ISSUE TITLE
homework_submit

### ISSUE THREAD

**Issue by henryinshanghai** [algorithm017/algorithm017#7]
#学号:G20200343140061
#姓名:刘恒
#班级:17期
#语言:java
#作业链接:https://github.com/henryinshanghai/algorithm017/tree/master/Week_01
#总结链接:https://github.com/henryinshanghai/algorithm017/tree/master/Week_01

**Comment by lousidy** [comment]
#学号:G20200343140094
#姓名:钟丹
#班级:17期
#语言: java
#作业及总结链接：https://github.com/lousidy/algorithm017/tree/master/Week_01

**Comment by Sunrise-123** [comment]
#学号:G20200343140149
#姓名:呼晓飞
#班级:17期
#语言: C++
#作业及总结链接：https://github.com/Sunrise-123/algorithm017/tree/master/Week_01

**Comment by dylanyg** [comment]
算法训练营
#学号: G20200343140157
#姓名: 姚刚
#班级: 17期
#语言: java
#作业链接: https://github.com/dylanyg/algorithm017/tree/master/Week_07
#总结链接: https://github.com/dylanyg/algorithm017/tree/master/Week_07
