### ISSUE TITLE
郑运荣的作业

### ISSUE THREAD

**Issue by kmadmin** [algorithm017/algorithm017#8]
#学号: G20200343140053
#姓名: 郑运荣
#班级: 第17期
#语言: JAVA
#作业链接:https://github.com/kmadmin/algorithm017/tree/master/Week_01
#总结链接:https://github.com/kmadmin/algorithm017/tree/master/Week_01

**Comment by dylanyg** [comment]
算法训练营
#学号: G20200343140157
#姓名: 姚刚
#班级: 17期
#语言: java
#作业链接: https://github.com/dylanyg/algorithm017/tree/master/Week_08
#总结链接: https://github.com/dylanyg/algorithm017/tree/master/Week_08
